#!/bin/bash
echo "Bash script v1.0"
read -r -p "Enter your bot location: " loc
read -r -p "Enter your bot name: " name
npm install telegraf 
npm install cron
echo "Creating /etc/systemd/system/support.service..."
printf "[Unit]\nDescription=support\n\n[Service]\nExecStart=/usr/bin/node $PWD/bin/support.js\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/support.service
echo "Creating /etc/systemd/system/${name}.service..."
printf "[Unit]\nDescription=${name}\n\n[Service]\nExecStart=/usr/bin/node ${loc}\n\n[Install]\nWantedBy=multi-user.target" > /etc/systemd/system/${name}.service
systemctl enable ${name}
systemctl enable support
